before_script:
  - 'sudo apt-get update'
  - 'sudo apt-get install chromium-browser'
  - 'sh -e /etc/init.d/xvfb start'
rvm:
  - ree
script:
  - 'bundle exec rake travis'
env:
  - DISPLAY=':99.0' # for xvfb & jasmine/evergreen